### ISSUE TITLE
Adding trankit, uralicNLP, simplemma, finnish-tagtools to lemmatization benchmark?

### ISSUE THREAD

**Issue by ogencoglu** [aajanki/finnish-pos-accuracy#1]
Any plans to update the lemmatization benchmarks with:

- [trankit](https://github.com/nlp-uoregon/trankit)
- [uralicNLP](https://github.com/mikahama/uralicNLP)
- [simplemma](https://github.com/adbar/simplemma/)
- [finnish-tagtools](https://korp.csc.fi/download/finnish-tagtools/)

?

**Comment by aajanki** [comment]
I have now included trankit, uralicNLP and simplemma.

If I understand correctly, the lemmatization and POS tagging features of finnish-tagtools are in fact implemented by FinnPos, which was already included here.

**Comment by ogencoglu** [comment]
Awesome, thanks!
